# easy_admin_bundle:
#     resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
#     prefix: /admin
#     type: annotation


easy_admin_bundle:
    resource: 'App\Controller\AdminController'
    prefix: /admin
    type: annotation
